FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt-get update && apt-get install -y \
    make \
    cmake \
    expect \
    git \
    ninja-build \
    python2 \
    unzip \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Some Samsung scripts reference /usr/bin/python.
RUN ln -sf /usr/bin/python2 /usr/bin/python

RUN useradd -m -s /bin/bash moonlight

USER moonlight
WORKDIR /home/moonlight

# Install Tizen Studio once.
RUN wget -nv -O web-cli_Tizen_Studio_5.6_ubuntu-64.bin 'https://download.tizen.org/sdk/Installer/tizen-studio_5.6/web-cli_Tizen_Studio_5.6_ubuntu-64.bin' && \
    chmod a+x web-cli_Tizen_Studio_5.6_ubuntu-64.bin && \
    ./web-cli_Tizen_Studio_5.6_ubuntu-64.bin --accept-license /home/moonlight/tizen-studio && \
    rm web-cli_Tizen_Studio_5.6_ubuntu-64.bin

ENV PATH=/home/moonlight/tizen-studio/tools/ide/bin:/home/moonlight/tizen-studio/tools:${PATH}

# Prepare Tizen signing certificates once.
RUN tizen certificate -a Moonlight -f Moonlight -p 1234 && \
    tizen security-profiles add \
      -n Moonlight \
      -a /home/moonlight/tizen-studio-data/keystore/author/Moonlight.p12 \
      -p 1234

# Workaround to package applications without gnome-keyring.
RUN sed -i 's|/home/moonlight/tizen-studio-data/keystore/author/Moonlight.pwd||' /home/moonlight/tizen-studio-data/profile/profiles.xml && \
    sed -i 's|/home/moonlight/tizen-studio-data/tools/certificate-generator/certificates/distributor/tizen-distributor-signer.pwd|tizenpkcs12passfordsigner|' /home/moonlight/tizen-studio-data/profile/profiles.xml

# Install Samsung NaCl SDK once.
RUN wget -nv -O nacl_sdk.zip 'https://developer.samsung.com/smarttv/file/55e181c4-fb5e-4d25-82df-f85b3b864dab' && \
    unzip nacl_sdk.zip && \
    rm nacl_sdk.zip

ENV NACL_SDK_ROOT=/home/moonlight/pepper_63

WORKDIR /home/moonlight